#!python3

"""Configuration for project documentation using Sphinx."""

# standard
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Union

# 3rd party
import keepachangelog

# move into project package
sys.path.insert(0, f"{Path(__file__).parent.parent.resolve()}")

# Package
from geoserver_manager import __about__

# -- Logging setup --
logger: logging.Logger = logging.getLogger(__name__)

# -- Project information --
changes: dict[str, dict] = keepachangelog.to_dict("../CHANGELOG.md")
# None until the first release: the site must not name a version nobody can install.
latest_version: Optional[str] = next(
    (v for v in changes if v not in ("Unreleased", "version_tag")), None
)

author: str = __about__.__author__
copyright: str = __about__.__copyright__
description: str = __about__.__summary__
official_repository_id: Optional[int] = None
project: str = __about__.__title__
version: str = __about__.__version__  # defined in metadata.txt
# Sphinx puts `release` in every page title; the version in development until
# there is a release, so no title reads "none yet".
release: str = latest_version or version

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# Only what the site actually uses. autosectionlabel labelled every heading of
# the included CHANGELOG, which has a "Fixed" under each version, so it warned
# on every build; nothing here uses a cross-reference role. intersphinx and
# viewcode need autodoc, and there is no API documentation: the plugin cannot
# be imported without QGIS, which the documentation job does not install.
extensions: list[str] = [
    # Sphinx included
    "sphinx.ext.githubpages",
    # 3rd party
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix: dict[str, str] = {".md": "markdown", ".rst": "restructuredtext"}
# The master toctree document.
master_doc: str = "index"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns: list[str] = [
    "_build",
    ".venv",
    "Thumbs.db",
    ".DS_Store",
    "_output",
    "ext_libs",
    "tests",
    "demo",
    "_autogenerated",
]

# Syntax highlighting, one theme each way round.
pygments_style: str = "friendly"
pygments_dark_style: str = "monokai"


# -- Options for HTML output -------------------------------------------------

# -- Theme

html_favicon: str = "static/branding/favicon.ico"
html_static_path = ["static/branding", "static/css"]
html_css_files = ["screenshots.css"]
html_theme = "furo"

# The brand blue and green are too light to read as text on white (3.3:1 and
# 3.6:1 against WCAG's 4.5:1 floor for body text), so each theme gets the
# variant that clears it: darkened on paper, lightened on ink. Measured, the
# way gui/theme.py measures the colours inside the plugin.
html_theme_options: dict[str, Union[bool, int, str, dict]] = {
    "light_logo": "wordmark.svg",
    "dark_logo": "wordmark-white.svg",
    "sidebar_hide_name": True,
    "source_repository": f"{__about__.__uri__}",
    "source_branch": "main",
    "source_directory": "docs/",
    "light_css_variables": {
        "color-brand-primary": "#00718f",
        "color-brand-content": "#00718f",
        "color-brand-visited": "#47791f",
    },
    "dark_css_variables": {
        "color-brand-primary": "#5ccbe8",
        "color-brand-content": "#5ccbe8",
        "color-brand-visited": "#9ed86a",
    },
}

# -- EXTENSIONS --------------------------------------------------------

# MyST Parser
myst_enable_extensions: list[str] = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
]

myst_substitutions: dict[str, str] = {
    "author": author,
    "date_update": datetime.now().strftime("%d %B %Y"),
    "description": description,
    "qgis_version_max": __about__.__plugin_md__.get("general").get(
        "qgismaximumversion"
    ),
    "qgis_version_min": __about__.__plugin_md__.get("general").get(
        "qgisminimumversion"
    ),
    "repo_url": __about__.__uri__,
    "title": project,
    "version": version,
    "release_version": latest_version or "none yet",
}

# Anchors for "page.md#a-heading" links, down to ### headings.
myst_heading_anchors: int = 3

myst_url_scheme: tuple[str, str, str] = ("http", "https", "mailto")


# -- Hooks --
def generate_qdt_snippet(_) -> None:
    """Generate QDT snippet for profiles.json files."""
    logger.info("=== START GENERATING QDT SNIPPET ===")

    output_path: Path = Path("./docs/static/_autogenerated/qdt_snippet.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    qdt_snippet: dict[str, Union[str, bool, int]] = {
        "name": "GeoServer Manager",
        "folder_name": "geoserver_manager",
        "official_repository": True,
        "plugin_id": official_repository_id,
        "version": f"{latest_version or version}",
    }

    with output_path.open("w", encoding="UTF8") as wf:
        wf.write(json.dumps(qdt_snippet, indent=4, sort_keys=True))


# launch setup
def setup(app) -> None:
    """Sphinx setup hook."""
    app.connect("builder-inited", generate_qdt_snippet)
